#!/bin/bash

# A bash script that can detect the secondary display connected and enable that to be the primary display.
# Should run continuously in i3 and if there's no secondary display connected, then the default should be set.

active_monitors=`xrandr --listactivemonitors`
IFS=' '
read -ra ARR<<<"$active_monitors"

#for i in "${temp[@]}";
    #do
        #echo "$i"
    #done
temp=${ARR[1]}

if [[ $temp > 2 ]];
then
    xrandr --output eDP-1-1 --off --output HDMI-1-2 --primary
fi

