#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot compton or picom if it exists

if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton --config $SCRIPTPATH/compton.conf &> /dev/null &
fi

#set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe


#set background
if [ -x "$(command -v nitrogen)" ]; then
  nitrogen --restore 
fi

if [ ! -z "S(xrandr | grep ' connected' |grep 'HDMI' | awk '{print $1}')" ]; then
  xrandr --output eDP-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI-2 --mode 1920x1080 --pos 0x0 --rotate normal
fi

#polybar -v

#index=0
#monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
#leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
#do 
  #barname="mainbar$index"
  #echo $barname
  #monitor=$monitor offsetx=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  #let index=index+1
#done


if [ -x "$(command -v polybar)" ]; then
  pkill polybar
  monitors="$(polybar -m | sed s/:.*// | tac)"
  while read -r display; do
    MONITOR=$display polybar -c "$SCRIPTPATH/polybar.config" barbase &> /dev/null &
  done <<< "$monitors"
  exit 0
fi
